stages:
  - build
  - security
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

  FRONTEND_IMAGE_NAME: "registry.gitlab.com/harshavardhan81860/yakkai-demo/frontend"
  IMAGE_TAG: $CI_COMMIT_REF_NAME

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

# -------------------------
# build
# -------------------------
build-frontend:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      command: ["--tls=false"]
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$IMAGE_TAG frontend/
    - docker push $CI_REGISTRY_IMAGE/frontend:$IMAGE_TAG
#---------------------
# Deploy 
#----------------------
deploy_frontend:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git
    - git config --global user.email "harsha81860@gmail.com"
    - git config --global user.name "harshavardhan81860"
    - git remote set-url origin https://gitlab-ci-token:glpat-AukbHntS6V6MtZIP03dGpmM6MQpvOjEKdTptaDBqMw8.01.1707a26lo@gitlab.com/harshavardhan81860/yakkai-demo.git
  script:
    - IMAGE_PATH="$CI_REGISTRY_IMAGE/frontend:$IMAGE_TAG"
    - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
    - /usr/bin/yq -i '.spec.template.spec.containers[0].image = "'"$IMAGE_PATH"'"' helm/yaakai/values/values-dev.yaml
    - git add helm/yaakai/values/values-dev.yaml
    - git commit -m "deploy frontend $IMAGE_TAG [skip ci]" || echo "No changes"
    - git pull origin $CI_COMMIT_BRANCH --rebase
    - git push origin HEAD:$CI_COMMIT_BRANCH
