stages:
  - triggers

trigger-backend:
  stage: triggers
  trigger:
    include: backend/.gitlab-ci-backend.yml
    strategy: depend

trigger-frontend:
  stage: triggers
  trigger:
    include: frontend/.gitlab-ci-frontend.yml
    strategy: depend