{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.backend.config.app.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          args:
            - "--config"
            - "/app/config/helm-dev.yaml"
          volumeMounts:
            - name: backend-config
              mountPath: /app/config
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
        - name: backend-config
          configMap:
            name: {{ .Values.backend.config.app.name }}-config
{{- end }}
