apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudforge.fullname" . }}-secret
  labels:
    {{- include "cloudforge.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret-key: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
